easy_breadcrumb.settings:
  type: config_object
  label: 'Easy Breadcrumb'
  mapping:
    include_invalid_paths:
      type: boolean
      label: 'Include invalid paths alias as plain-text segments'
    excluded_paths:
      type: text
      label: 'Paths to be excluded while generating segments'
    replaced_titles:
      type: text
      label: 'Titles to be replaced with synonyms'
    include_home_segment:
      type: boolean
      label: 'Include the front page as a segment in the breadcrumb'
    home_segment_title:
      type: label
      label: 'Title for the front page segment in the breadcrumb'
      translatable: true
    home_segment_keep:
      type: integer
      label: 'Display the front page segment on the front page'
    include_title_segment:
      type: boolean
      label: 'Include the current page as a segment in the breadcrumb'
    title_from_page_when_available:
      type: boolean
      label: 'Use the real page title when available'
    title_segment_as_link:
      type: boolean
      label: 'Make the page title segment a link'
    segments_separator:
      type: text
      label: 'Segments Separator'
    use_menu_title_as_fallback:
      type: boolean
      label: 'Use menu title as fallback instead of raw path component'
    remove_repeated_segments:
      type: boolean
      label: 'Remove repeated identical segments'
    language_path_prefix_as_segment:
      type: boolean
      label: 'Use language path prefix as segment'
    absolute_paths:
      type: boolean
      label: 'Use absolute path for Breadcrumb links'
    hide_single_home_item:
          type: boolean
          label: 'Hide the breadcrumb when it only links to the home page and nothing more'
